Design/dead cleanup
RoboTeamTwente/roboteam_utils pull request #69
Opened 2020-05-08 10:55 UTC by HaicoDorenbos

Cleanup of all dead code in the Roboteam_utils repository.

2020-05-08 13:31 UTC, rolfvdhulst requested changes
Please don´t delete the Tube class. It´s an important shape for ball placement and will be necessary in the future.

EDIT: Jesse just told me he needed it already but was not aware of it's existence.

2020-05-12 07:38 UTC, timovdk commented on CMakeLists.txt
> -        include/roboteam_utils/Tube.h
Tube is used now

2020-05-12 07:39 UTC, timovdk commented on CMakeLists.txt
> -        #        include/roboteam_utils/Cone.h
Cone is nice to keep. Tube was unused for the whole year, but as of yesterday it is used. I propose to keep this shape as well for the same reason.

2020-05-12 07:40 UTC, timovdk requested changes
Please re-add Tube since Tube is used again as of yesterday

2020-05-12 08:32 UTC, rolfvdhulst commented
I would disagree with using cone personally because it is very legacy (I believe from 2016/2017), so you will want to rewrite the code to work properly at some point.

2020-05-13 08:20 UTC, HaicoDorenbos commented
I did not know that my PR have such positive influence. By removing code I remind others that of possible code clones.

2020-05-13 08:27 UTC, HaicoDorenbos commented
Tube has been re-added.

2020-05-13 09:00 UTC, rolfvdhulst commented
I feel like this is still missing the point. If the code is tested and works fine, I don't think we should remove it. It's the utils repository after all, and this way people can use it to prevent code clones as you mentioned yourself haico. Especially code that was recently added such as statistics /Triangle should really not be removed IMO.

2020-05-13 09:01 UTC, rolfvdhulst commented
In my opinion: if a class/function is tested and works correctly, don't remove it.

2020-05-13 09:07 UTC, HaicoDorenbos commented
Don't add new functionality if it is not used directly

2020-05-13 09:10 UTC, rolfvdhulst commented
Sure, but all of these classes *should* be used in our code at some point. Also 'usage' can really vary and does not mean they hav to be directly used during our code. I needed the statistics functions a lot when testing roboteam_world earlier this year on branches, where I removed usage later again after the code/models were verified to work correctly for example.

2020-05-13 09:11 UTC, rolfvdhulst commented
I disagree with the premise our code base is too big though. It's actually not even close to being big enough to cover all functionality needed for the robocup. If running CLion is a problem for you, then I would not see that as a codebase issue but as an IDE issue.

2020-05-13 09:14 UTC, HaicoDorenbos commented
> Sure, but all of these classes _should_ be used in our code at some point. Also 'usage' can really vary and does not mean they hav to be directly used during our code. I needed the statistics functions a lot when testing roboteam_world earlier this year on branches, where I removed usage later again after the code/models were verified to work correctly for example.

Theoretically it should be used. But you know what happens in practise, future teams forget that this code exists and the code remains dead...

2020-05-13 09:14 UTC, rolfvdhulst commented
And, by continuously asking people to readd the code later, you tend to create a lot more code clones as not everyone is aware of the existence of certain classes. Especially utility like this, should just be available for use IMO. The compile time impact of single files is actually quite minimal (and actually none in the case of header only classes).

2020-05-13 09:16 UTC, rolfvdhulst commented
Is it a problem if there is dead but functionally correct code in our system? I don't think so. If it's not correct, then it's a problem and can go.

2020-05-13 09:16 UTC, HaicoDorenbos commented
Also dead code causes more development time. Dead code should be properly documented, designed, tested, analysed for bugs, performance optimized, ... 

I am not willing to do that for code that is not used at all

2020-05-13 09:19 UTC, HaicoDorenbos commented
But I can make an agreement with you. I can store all the dead code on a separate branch and if someone needs it then he can use it (however then he should also improve the documentation, integrate it in the current design, re-evaluate the test cases, analyse the code for bugs, optimize the code in performance, etc.)

2020-05-13 09:37 UTC, rolfvdhulst commented
I would still disagree with that.  Utilities should just be ready for use. If you put them on a seperate branch you might as well remove them as no one ever looks back to old branches unless they are very important (e.g. we played a match on them).

2020-05-13 09:38 UTC, HaicoDorenbos commented
So you want me to document/redesign/analyze/optimize all this dead code?

2020-05-13 12:16 UTC, HaicoDorenbos commented
We decided to add a dead code comment tag at places where there is dead code

2020-05-13 13:31 UTC, HaicoDorenbos commented
All deadcode has been marked and removed from CMakeList to ensure that it is really dead code and to speed up compilation.

2020-05-15 09:16 UTC, timovdk approved these changes

2020-05-15 09:20 UTC, rolfvdhulst approved these changes

2020-05-18 08:14 UTC, merged