Feature/robot shape
RoboTeamTwente/roboteam_utils pull request #88
Opened 2020-10-18 20:10 UTC by rolfvdhulst

2021-09-25 20:51 UTC, mamiksik commented
Hey, I wasn't looking to much into codestyle this time. The code quality overall looks good. Tests are very sweet! 

I suggest squishing the commits into one (I think commits like _fix warning_, _add suggested change_ don't carry much value in git history). and adding one descriptive commit message explaning what is this merge traning to achieve, why, what decision have been made etc. (I recomend: https://chris.beams.io/posts/git-commit/. It's an amazing article about commit messages!)

2021-12-15 19:27 UTC, rolfvdhulst commented
We can squish the commits when we merge, no? That way that commit gets a specific message. Please review, it's been open for almost 1.5 years

2021-12-23 08:25 UTC, alexander-de-ranitz commented on test/StateMachineTest.cpp
> +    //test clamping: TODO: these segfault (not clamped correctly?)
Is this TODO still relevant? Or was this solved in this fix?

2021-12-23 08:58 UTC, alexander-de-ranitz commented on include/roboteam_utils/LineSegment.h
> +    [[nodiscard]] std::optional<Vector2> firstIntersects(const LineSegment &segment) const;
Documentation would be nice. It is not immediately obvious what this function does.

2022-01-22 11:55 UTC, mamiksik requested changes

2022-01-22 11:55 UTC, mamiksik commented on test/utils/RobotShapeTest.cpp
> +using namespace rtt;
new line?

2022-01-22 11:55 UTC, mamiksik commented on test/utils/RobotShapeTest.cpp
> +    //Thesse are very crucial that they are in the right order,
typo

2022-01-22 11:55 UTC, mamiksik commented on test/utils/RobotShapeTest.cpp
> +    double diff = sqrt(0.1*0.1-0.05*0.05);
What are these numbers?

2022-01-22 11:55 UTC, mamiksik commented on src/utils/RobotShape.cpp
> +        return {};//This should never be hit as circle intersection always hits atleast two.
Log error?

2022-01-22 11:55 UTC, mamiksik commented on src/utils/Polynomial.cpp
> +    int numberQuadraticSolutions(double a, double b, double c) {
countQuadraticSolutions?

2022-01-22 11:55 UTC, mamiksik commented on test/utils/StaticVectorTest.cpp
> +
Why this line?

2022-01-22 11:59 UTC, alexander-de-ranitz commented on include/roboteam_utils/LineSegment.h
> +    [[nodiscard]] bool preciseDoesIntersect(const LineSegment&line) const;
Documentation would be nice. What is the difference with the non-precise doesIntersect and when should which be used?

2022-01-22 11:59 UTC, alexander-de-ranitz commented on test/utils/Vector2Test.cpp
> +//}
Why was this test commented out? If it isn't useful, perhaps remove it.

2022-01-22 11:59 UTC, alexander-de-ranitz commented on src/utils/Polynomial.cpp
> +        } else if (discriminant == 0) {
Why do this check only here? Is this not also useful in solveQuadratic and solveQuadraticPositiveA?

2022-01-22 11:59 UTC, alexander-de-ranitz commented on src/utils/Polynomial.cpp
> +        } else if (discriminant == 0) {
In general, what is the difference between solveQuadratic and solveQuadraticVector? Functionality seems to essentially be the exact same.

2022-01-22 12:01 UTC, rolfvdhulst commented on test/utils/RobotShapeTest.cpp
> +    double diff = sqrt(0.1*0.1-0.05*0.05);
Fixed them to be variables at the start of the test (no more hardcoded numbers)

2022-01-22 12:18 UTC, rolfvdhulst commented on test/utils/StaticVectorTest.cpp
> +
idk.

2022-01-22 12:18 UTC, rolfvdhulst commented on test/utils/Vector2Test.cpp
> +//}
The function was removed on development (I removed the test now).

2022-01-22 12:18 UTC, rolfvdhulst commented on src/utils/Polynomial.cpp
> +        } else if (discriminant == 0) {
Functionality is very similar, but vector only returns as many roots as there actually are. Sometimes, a pair may be more convenient and sometimes a vector is more convenient. In this case, the vector might in particular return only one value whereas the make_pair always returns two (this is sometimes useful, as in some cases you always need to check both, and in some cases you only need the highest/lowest etc.).

2022-01-22 13:09 UTC, mamiksik approved these changes

2022-01-22 13:10 UTC, merged